# Development environment - only essential services
# Run backend and frontend manually for development

services:
  # PostgreSQL database
  postgres:
    image: postgres:15-alpine
    container_name: claude-web-postgres-dev
    environment:
      POSTGRES_USER: claude_web
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: claude_web
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres-dev:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    networks:
      - claude-web-dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U claude_web"]
      interval: 10s
      timeout: 5s
      retries: 5

  # SSH proxy service
  sshpiper:
    build:
      context: ./docker/sshpiper
      dockerfile: Dockerfile
    container_name: claude-web-sshpiper-dev
    ports:
      - "2222:2222"
    volumes:
      - ./sshpiper:/sshpiper:rw
    environment:
      SSHPIPER_PORT: "2222"
      SSHPIPER_SERVER_KEY: "/sshpiper/hostkeys/ssh_host_ed25519_key"
      SSHPIPER_WORKINGDIR_ROOT: "/sshpiper/workingdir"
      SSHPIPER_LOG_LEVEL: debug
      SSHPIPER_UPSTREAM_DRIVER: workingdir
    networks:
      - claude-web-dev
    restart: unless-stopped

  # Inlets tunnel server
  inlets:
    build:
      context: ./docker/inlets-server
      dockerfile: Dockerfile
    container_name: claude-web-inlets-dev
    ports:
      - "8090:8090"  # Control plane (WebSocket)
      - "8080:8080"  # Data plane (HTTP traffic)
      - "8091:8091"  # Status API
    volumes:
      - ./data/inlets:/data
    environment:
      INLETS_TOKEN: "${INLETS_TOKEN:-development-token-change-in-production}"
      INLETS_DOMAIN: "${INLETS_DOMAIN:-tunnel.localhost}"
      INLETS_CONTROL_PORT: "8090"
      INLETS_DATA_PORT: "8080"
      STATUS_PORT: "8091"
    networks:
      - claude-web-dev
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8091/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  claude-web-dev:
    name: claude-web-dev
    driver: bridge
  claude-web-bridge:
    name: claude-web-bridge
    driver: bridge
    external: true
